const state={token:localStorage.getItem('ci_token')||'',dashboard:null,currentImport:null,suggestions:null,activeView:'processes',processLimit:20,importLimit:50};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const statusNames={preparation:'Em preparação',waiting_documents:'Aguardando documentos',waiting_signature:'Aguardando assinatura',ready:'Pronta para envio',submitted:'Enviada à FAPESP',analysis:'Em análise',diligence:'Em diligência',authorized:'Autorizada',execution:'Em execução',completed:'Concluída',cancelled:'Cancelada'};
const categoryNames={signed_form:'Formulário assinado',winner_proposal:'Proforma vencedora',coverage_proposal:'Proposta de cobertura',coverage_merged:'Propostas de cobertura reunidas',exclusivity:'Carta de exclusividade',price_reasonableness:'Razoabilidade de preços',clarification:'Esclarecimento',other:'Outro'};
async function api(path,opts={}){opts.headers={...(opts.headers||{}),'Content-Type':'application/json'};if(state.token)opts.headers.Authorization=`Bearer ${state.token}`;const r=await fetch(path,opts);const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Falha na operação');return data}
function money(v,c){return `${c} ${Number(v).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:4})}`}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),3500)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function boot(){const s=await api('/api/session');$('#version').textContent=s.version;if(s.authenticated){showApp();return}$('#auth').classList.remove('hidden');$('#auth-copy').textContent=s.configured?'Entre para continuar.':'Crie a senha inicial do aplicativo.';$('#auth-form').dataset.mode=s.configured?'login':'setup'}
$('#auth-form').addEventListener('submit',async e=>{e.preventDefault();try{const mode=e.currentTarget.dataset.mode;const d=await api(`/api/${mode}`,{method:'POST',body:JSON.stringify({password:$('#password').value})});state.token=d.token;localStorage.setItem('ci_token',d.token);$('#auth').classList.add('hidden');showApp()}catch(err){$('#auth-error').textContent=err.message}});
async function showApp(){$('#app').classList.remove('hidden');await loadDashboard()}
async function loadSuggestions(){state.suggestions=await api('/api/suggestions');const set=(id,rows)=>{$(id).innerHTML=rows.map(v=>`<option value="${esc(v)}">`).join('')};set('#researchers',state.suggestions.researchers);set('#processes-list',state.suggestions.processes);set('#exporters',state.suggestions.exporters);set('#manufacturers',state.suggestions.manufacturers);set('#representatives',state.suggestions.representatives)}
async function loadDashboard(){state.dashboard=await api('/api/dashboard');state.processLimit=20;state.importLimit=50;renderDashboard();if(state.activeView==='imports')renderImports()}
function renderDashboard(){if(!state.dashboard)return;const q=$('#search').value.trim().toLocaleLowerCase('pt-BR');const filter=$('#status-filter').value;const matches=state.dashboard.processes.map(p=>({...p,imports:p.imports.filter(i=>(!filter||i.status===filter)&&(!q||`${p.number} ${p.researcher_name} ${i.exporter} ${i.manufacturer} ${i.representative} ${i.proforma_number}`.toLocaleLowerCase('pt-BR').includes(q)))})).filter(p=>p.imports.length);const visible=matches.slice(0,state.processLimit);const html=visible.map(p=>{const totals=Object.entries(p.totals).map(([c,v])=>`<div class="money"><span>Autorizadas/concluídas</span><strong>${money(v,c)}</strong></div>`).join('')||'<span class="muted">Sem valores autorizados</span>';const shown=p.imports.slice(0,10);const remaining=p.imports.length-shown.length;return `<article class="process"><div class="process-head"><div><div class="process-number">Processo ${esc(p.number)}</div><strong>${esc(p.researcher_name)}</strong><div class="muted">${p.imports.length} importação(ões)</div></div><div class="totals">${totals}</div></div><div class="table-wrap"><table><thead><tr><th>Fornecedor / proforma</th><th>Valor</th><th>Situação</th><th>Próxima providência</th><th></th></tr></thead><tbody>${shown.map(i=>`<tr><td><strong>${esc(i.exporter)}</strong>${i.needs_review?'<span class="review-tag">Conferir</span>':''}<div class="muted">${esc(i.proforma_number||'Sem número')}</div></td><td>${money(i.value_amount,i.currency)}</td><td><span class="badge ${i.status}"><span class="dot"></span>${statusNames[i.status]||i.status}</span></td><td>${esc(i.next_action||'—')}</td><td><button class="secondary open-import" data-id="${i.id}">Abrir</button></td></tr>`).join('')}</tbody></table>${remaining>0?`<div class="process-more">Mais ${remaining} importação(ões). Use a pesquisa ou a tela Importações.</div>`:''}</div></article>`}).join('');const more=matches.length>visible.length?`<div class="load-more"><button id="more-processes" class="secondary">Mostrar mais processos (${visible.length} de ${matches.length})</button></div>`:'';$('#process-list').innerHTML=(html+more)||'<div class="panel">Nenhuma importação encontrada.</div>';$$('.open-import').forEach(b=>b.onclick=()=>openImport(b.dataset.id));if($('#more-processes'))$('#more-processes').onclick=()=>{state.processLimit+=20;renderDashboard()}}
$('#search').oninput=()=>{state.processLimit=20;renderDashboard()};$('#status-filter').onchange=()=>{state.processLimit=20;renderDashboard()};
function renderImports(){if(!state.dashboard)return;const q=$('#imports-search').value.trim().toLocaleLowerCase('pt-BR');const filter=$('#imports-status-filter').value;const rows=state.dashboard.processes.flatMap(p=>p.imports.map(i=>({...i,process_number:p.number,researcher_name:p.researcher_name}))).filter(i=>(!filter||i.status===filter)&&(!q||`${i.process_number} ${i.researcher_name} ${i.exporter} ${i.manufacturer} ${i.representative} ${i.proforma_number}`.toLocaleLowerCase('pt-BR').includes(q))).sort((a,b)=>String(b.opened_on).localeCompare(String(a.opened_on))||b.id-a.id);const visible=rows.slice(0,state.importLimit);const html=visible.map(i=>`<tr><td><strong>${esc(i.exporter)}</strong>${i.needs_review?'<span class="review-tag">Conferir</span>':''}<div class="muted">${esc(i.proforma_number||'Sem número')}</div></td><td><strong>${esc(i.process_number)}</strong><div class="muted">${esc(i.researcher_name)}</div></td><td>${money(i.value_amount,i.currency)}</td><td><span class="badge ${i.status}"><span class="dot"></span>${statusNames[i.status]||i.status}</span></td><td>${esc(i.next_action||'—')}</td><td><button class="secondary open-import-list" data-id="${i.id}">Abrir</button></td></tr>`).join('');const more=rows.length>visible.length?`<button id="more-imports" class="secondary">Mostrar mais (${visible.length} de ${rows.length})</button>`:'';$('#imports-list').innerHTML=html?`<div class="panel import-list-panel"><div class="table-wrap"><table><thead><tr><th>Fornecedor / proforma</th><th>Processo / pesquisador</th><th>Valor</th><th>Situação</th><th>Próxima providência</th><th></th></tr></thead><tbody>${html}</tbody></table></div><div class="list-count">Exibindo ${visible.length} de ${rows.length} importação(ões) ${more}</div></div>`:'<div class="panel">Nenhuma importação encontrada.</div>';$$('.open-import-list').forEach(b=>b.onclick=()=>openImport(b.dataset.id));if($('#more-imports'))$('#more-imports').onclick=()=>{state.importLimit+=50;renderImports()}}
$('#imports-search').oninput=()=>{state.importLimit=50;renderImports()};$('#imports-status-filter').onchange=()=>{state.importLimit=50;renderImports()};
async function showImportDialog(i=null){if(!state.suggestions)await loadSuggestions();const f=$('#import-form');f.reset();$('#form-error').textContent='';f.import_id.value=i?.id||'';f.opened_on.value=i?.opened_on||new Date().toISOString().slice(0,10);for(const name of ['researcher_name','process_number','exporter','manufacturer','representative','proforma_number','currency','value_amount','nature','price_mode','next_action','notes'])if(i&&f.elements[name])f.elements[name].value=i[name]??'';$('#import-dialog-title').textContent=i?'Editar importação':'Nova importação';$('#save-import').textContent=i?'Salvar alterações':'Criar importação';$('#import-dialog').showModal()}
$('#new-import').onclick=()=>showImportDialog();$('#new-import-list').onclick=()=>showImportDialog();$$('.close-import').forEach(b=>b.onclick=()=>$('#import-dialog').close());
$('#import-form').addEventListener('submit',async e=>{e.preventDefault();const obj=Object.fromEntries(new FormData(e.currentTarget));const id=obj.import_id;try{const d=await api(id?`/api/imports/${id}`:'/api/imports',{method:id?'PUT':'POST',body:JSON.stringify(obj)});$('#import-dialog').close();state.suggestions=null;await loadDashboard();await openImport(id||d.id);toast(id?'Importação atualizada':'Importação criada')}catch(err){$('#form-error').textContent=err.message}});
async function openImport(id){state.currentImport=await api(`/api/imports/${id}`);if(state.currentImport.error)return toast(state.currentImport.error);$$('.view').forEach(v=>v.classList.add('hidden'));$('#detail-view').classList.remove('hidden');renderDetail()}
function renderDetail(){const d=state.currentImport,i=d.import;const docs=d.documents.map(x=>`<div class="doc-row"><div><strong>${esc(x.label)}</strong><div class="muted">${esc(categoryNames[x.category]||x.category)} • versão ${x.version} • ${esc(x.original_name)}</div></div><div class="row-actions"><button class="secondary download-doc" data-id="${x.id}" data-name="${esc(x.original_name)}">Baixar</button><button class="secondary edit-doc" data-id="${x.id}">Editar</button><button class="danger delete-doc" data-id="${x.id}">Excluir</button></div></div>`).join('')||'<p>Nenhum documento anexado.</p>';$('#detail').innerHTML=`<div class="detail-head"><div><h1>${esc(i.exporter)} — ${esc(i.proforma_number||'Sem proforma')}</h1><p>Processo ${esc(i.process_number)} • ${esc(i.researcher_name)} • ${money(i.value_amount,i.currency)}</p>${i.needs_review?'<p class="review-note">Registro histórico pendente de conferência.</p>':''}</div><div class="detail-actions"><button id="edit-import" class="secondary">Editar</button>${i.status==='completed'?'<button id="reactivate" class="secondary">Reativar</button>':''}<button id="delete-import" class="danger">Excluir importação</button><button id="add-doc" class="primary">+ Documento</button><button id="merge" class="secondary">Reunir propostas de cobertura</button></div></div><div class="panel"><h2>Resumo</h2><p><span class="badge ${i.status}"><span class="dot"></span>${statusNames[i.status]}</span></p><p><strong>Próxima providência:</strong> ${esc(i.next_action||'Não informada')}</p><p><strong>Natureza:</strong> ${i.nature==='service'?'Serviço no exterior':'Bens ou insumos'} • <strong>Formação do preço:</strong> ${i.price_mode==='three_quotes'?'Três ou mais propostas':'Menos de três propostas'}</p></div><div class="panel"><h2>Documentos</h2><div class="doc-grid">${docs}</div></div><div class="panel"><h2>Histórico</h2>${d.events.map(e=>`<div class="doc-row"><div>${esc(e.description)}<div class="muted">${new Date(e.created_at).toLocaleString('pt-BR')}</div></div></div>`).join('')}</div>`;$('#add-doc').onclick=()=>showDocDialog();$('#merge').onclick=mergeCoverage;$('#edit-import').onclick=()=>showImportDialog(i);$('#delete-import').onclick=deleteImport;if($('#reactivate'))$('#reactivate').onclick=reactivateImport;$$('.download-doc').forEach(b=>b.onclick=()=>downloadDocument(b.dataset.id,b.dataset.name));$$('.edit-doc').forEach(b=>b.onclick=()=>showDocDialog(d.documents.find(x=>x.id==b.dataset.id)));$$('.delete-doc').forEach(b=>b.onclick=()=>deleteDocument(b.dataset.id))}
async function deleteImport(){const i=state.currentImport.import;if(!confirm(`Excluir definitivamente a importação de ${i.exporter}? Todos os documentos anexados também serão excluídos.`))return;try{await api(`/api/imports/${i.id}`,{method:'DELETE'});$('#detail-view').classList.add('hidden');$(`#${state.activeView}-view`).classList.remove('hidden');await loadDashboard();await loadSuggestions();toast('Importação excluída')}catch(err){toast(err.message)}}
async function reactivateImport(){const i=state.currentImport.import;if(!confirm('Reativar esta importação e devolvê-la para “Em preparação”?'))return;try{await api(`/api/imports/${i.id}/status`,{method:'POST',body:JSON.stringify({status:'preparation',next_action:'Revisar importação reativada'})});await openImport(i.id);toast('Importação reativada')}catch(err){toast(err.message)}}
function showDocDialog(doc=null){const f=$('#doc-form');f.reset();$('#doc-error').textContent='';f.import_id.value=state.currentImport.import.id;f.document_id.value=doc?.id||'';if(doc){f.category.value=doc.category;f.label.value=doc.label;f.signed.checked=!!doc.signed}f.file.required=!doc;$('#doc-file-label').classList.toggle('hidden',!!doc);$('#doc-dialog-title').textContent=doc?'Editar documento':'Anexar documento';$('#save-doc').textContent=doc?'Salvar alterações':'Anexar';$('#doc-dialog').showModal()}
$$('.close-doc').forEach(b=>b.onclick=()=>$('#doc-dialog').close());
async function downloadDocument(id,name){try{if(window.pywebview?.api?.save_document){const d=await window.pywebview.api.save_document(Number(id));if(d.cancelled)return;if(!d.ok)throw new Error(d.error||'Falha ao salvar documento');toast(`Documento salvo em ${d.path}`);return}const r=await fetch(`/api/documents/${id}/download`,{headers:{Authorization:`Bearer ${state.token}`}});if(!r.ok)throw new Error('Falha ao baixar documento');const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(err){toast(err.message)}}
$('#doc-form').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),id=fd.get('document_id');try{if(id){await api(`/api/documents/${id}`,{method:'PUT',body:JSON.stringify({category:fd.get('category'),label:fd.get('label'),signed:fd.get('signed')==='on'})})}else{const file=fd.get('file');const content=await fileToData(file);await api(`/api/imports/${fd.get('import_id')}/documents`,{method:'POST',body:JSON.stringify({name:file.name,content_base64:content,category:fd.get('category'),label:fd.get('label'),signed:fd.get('signed')==='on'})})}$('#doc-dialog').close();await openImport(fd.get('import_id'));toast(id?'Documento atualizado':'Documento anexado')}catch(err){$('#doc-error').textContent=err.message}});
async function deleteDocument(id){const doc=state.currentImport.documents.find(x=>x.id==id);if(!confirm(`Excluir o documento “${doc?.label||''}”?`))return;try{await api(`/api/documents/${id}`,{method:'DELETE'});await openImport(state.currentImport.import.id);toast('Documento excluído')}catch(err){toast(err.message)}}
function fileToData(file){return new Promise((ok,fail)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=fail;r.readAsDataURL(file)})}
async function mergeCoverage(){const candidates=state.currentImport.documents.filter(d=>d.category==='coverage_proposal'&&d.status==='current');if(candidates.length<2)return toast('Anexe ao menos duas propostas de cobertura');try{await api(`/api/imports/${state.currentImport.import.id}/merge-coverage`,{method:'POST',body:JSON.stringify({document_ids:candidates.map(x=>x.id)})});await openImport(state.currentImport.import.id);toast('PDF de cobertura gerado')}catch(err){toast(err.message)}}
$('#back').onclick=()=>{$('#detail-view').classList.add('hidden');$(`#${state.activeView}-view`).classList.remove('hidden');loadDashboard()};
async function backup(){try{if(window.pywebview?.api?.save_backup){const d=await window.pywebview.api.save_backup();if(d.cancelled)return;if(!d.ok)throw new Error(d.error||'Falha ao salvar backup');$('#backup-result').textContent=`Backup salvo em: ${d.path}`;toast('Backup salvo com sucesso');return}const d=await api('/api/backup',{method:'POST',body:'{}'});$('#backup-result').textContent=`Backup interno criado: ${d.file}`;toast('Backup criado com sucesso')}catch(err){toast(err.message)}}$('#backup-settings').onclick=backup;
$('#import-history').onclick=async()=>{const file=$('#history-file').files[0];if(!file)return toast('Selecione o arquivo IMPORTAÇÕES.zip');if(!file.name.toLowerCase().endsWith('.zip'))return toast('Selecione um arquivo ZIP');if(!confirm(`Importar o acervo “${file.name}”? A operação pode levar alguns minutos e não altera os registros existentes.`))return;const b=$('#import-history');b.disabled=true;b.textContent='Importando...';$('#history-progress').textContent='Enviando e processando o arquivo. Não feche o aplicativo.';try{const r=await fetch('/api/historical-import',{method:'POST',headers:{Authorization:`Bearer ${state.token}`,'Content-Type':'application/zip'},body:file});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Falha ao importar o acervo');$('#history-result').textContent=d.imports?`${d.imports} importações e ${d.documents} documentos acrescentados.`:'O acervo já havia sido importado.';$('#history-progress').textContent='Importação concluída.';await loadSuggestions();await loadDashboard();toast('Acervo histórico processado')}catch(err){$('#history-progress').textContent='';toast(err.message)}finally{b.disabled=false;b.textContent='Importar arquivo selecionado'}};
$('#restore').onclick=async()=>{const file=$('#restore-file').files[0];if(!file)return toast('Selecione um backup ZIP');if(!confirm('Restaurar este backup? Os dados atuais serão preservados em um backup de segurança.'))return;try{const content=await fileToData(file);const d=await api('/api/restore',{method:'POST',body:JSON.stringify({content_base64:content})});toast(`Backup restaurado. Cópia de segurança: ${d.safety_backup}`);await loadSuggestions();await loadDashboard()}catch(err){toast(err.message)}};
$$('.nav').forEach(b=>b.onclick=()=>{state.activeView=b.dataset.view;$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.add('hidden'));$(`#${state.activeView}-view`).classList.remove('hidden');if(state.activeView==='imports')renderImports()});
boot().catch(err=>{document.body.innerHTML=`<pre>Falha ao iniciar: ${esc(err.message)}</pre>`});
